// AUTH
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const FETCH_USER = 'FETCH_USER';

// PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_STATUS = 'GET_PROFILE_STATUS';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

// ERROR HANDLING
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CHANGE_ERRORS = 'CHANGE_ERRORS';

// DASHBOARD
export const GET_RATE = 'GET_RATE';
